apiVersion: argoproj.io/v1alpha1
kind: Application
metedata:
  name: second-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source: 
    repoURL: https://github.com/...
    targetRevision: HEAD
    path: environment/stage/second-app
  destination:
    server: https://kubernetes.default.svc
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOption:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true    

















